#!/bin/bash
# Munin Plugin for DHT22.
LANG=C

# set device info.
SENSOR=2302
GPIO=4

# Value Correction.
TempCorrection=0
HumidityCorrection=-2.8

# Configuration.
if [ "$1" = "config" ]; then
    echo 'graph_title Room Temperature/Humidity'
    # echo 'graph_args --base 1000'
    # echo 'graph_args --base 1000 --upper-limit 50 --lower-limit 0'
    echo 'graph_category Room'
    echo 'temp.label Temperature (C)'
    echo 'temp.type GAUGE'
    echo 'temp.min -40'
    echo 'temp.max 80'
    echo 'temp.draw LINE2'
    echo 'humidity.label Humidity (%)'
    echo 'humidity.type GAUGE'
    echo 'humidity.min 0'
    echo 'humidity.max 100'
    echo 'humidity.draw LINE2'
    exit 0
fi

# Set Variables.
STAT=1
RCNT=1
MAX_RETRY=2

# It is adjusted to return 0 in the case of an error after a certain number of retries.
while [ $STAT -ne 0 ]
do
    DHT=`/usr/local/bin/dht.py $SENSOR $GPIO`
    STAT=$?
    if [ $RCNT -eq $MAX_RETRY ]; then
        A=`echo "-1 * $TempCorrection" | bc`
        B=`echo "-1 * $HumidityCorrection" | bc`
        DHT="Temp=$A*  Humidity=$B%"
        STAT=0
    fi
    RCNT=$((++RCNT))
done

# Parse
Temperature=`echo $DHT | sed -e 's/Temp\=\(.*\)\*.*$/\1/;'`
Humidity=`echo $DHT | sed -e 's/^.*Humidity\=\(.*\)\%.*$/\1/;'`

# Value set & Correction
echo temp.value `echo "$Temperature + $TempCorrection" | bc`
echo humidity.value `echo "$Humidity + $HumidityCorrection" | bc`

exit 0
